name: Go Tests and Examples

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run Tests and Examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Run Tests
        run: go test -v ./pkg/...

      - name: Generate Coverage Report
        run: |
          mkdir -p coverage
          go test -coverprofile=coverage/coverage.out ./pkg/...
          go tool cover -func=coverage/coverage.out
        
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/
          
      - name: Verify Examples Compile
        run: |
          echo "Compiling examples to verify they are correct..."
          go build -o /dev/null ./examples/01_basic_setup/main.go
          go build -o /dev/null ./examples/02_download_index/main.go
          go build -o /dev/null ./examples/03_list_packages/main.go
          go build -o /dev/null ./examples/04_get_statistics/main.go
          go build -o /dev/null ./examples/05_security_advisories/main.go
          echo "All examples compiled successfully!" 